defaults:
  - simulation: base
  - rendering: gl
  - execution: no_graph
  - logging: hdf5
  - engine: axion_pos
  - _self_

# Use the recommended hybrid approach for project names
project_name: ${hydra:job.name}
