defaults:
  - simulation: base
  - rendering: gl
  - execution: cuda_graph
  - logging: disabled
  - engine: axion_vel
  - _self_

# Use the recommended hybrid approach for project names
project_name: ${hydra:job.name}
